name: Clang Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build with Clang (${{ matrix.configuration }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang make

      - name: Configure with CMake (Clang)
        run: |
          cmake -B build/${{ matrix.configuration }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} \
            -DCMAKE_C_COMPILER=clang

      - name: Build with Clang
        run: cmake --build build/${{ matrix.configuration }} -- -j

      - name: Run tests (fail if any test fails)
        working-directory: build/${{ matrix.configuration }}
        run: ctest --output-on-failure
