name: MSVC Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build with Visual Studio C++
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure with CMake (Visual Studio generator)
        run: cmake -B build -G "Visual Studio 17 2022" -A x64

      - name: Build the release version with MSVC
        run: cmake --build build --config Release

      - name: Run the release version tests (fail if any test fails)
        working-directory: build
        run: ctest --output-on-failure -C Release

      - name: Build the debug version with MSVC
        run: cmake --build build --config Debug

      - name: Run the debug version tests (fail if any test fails)
        working-directory: build
        run: ctest --output-on-failure -C Debug
